/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.problem_2;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author dell
 */
public class AboutPageDM extends javax.swing.JFrame {

    /**
     * Creates new form AboutPageDM
     */
    public AboutPageDM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        amer = new javax.swing.JLabel();
        batool = new javax.swing.JLabel();
        george = new javax.swing.JLabel();
        amjad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(35, 31, 32));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel2.setLayout(null);

        jButton2.setBackground(new java.awt.Color(35, 31, 32));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/problem_2/Light Mode Button.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(925, 32, 43, 20);

        jButton3.setBackground(new java.awt.Color(35, 31, 32));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/problem_2/Gold About.png"))); // NOI18N
        jButton3.setBorder(null);
        jPanel2.add(jButton3);
        jButton3.setBounds(0, 467, 250, 60);

        jButton4.setBackground(new java.awt.Color(35, 31, 32));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/problem_2/FormulaDM.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(32, 320, 104, 23);

        jButton5.setBackground(new java.awt.Color(35, 31, 32));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/problem_2/TreeDM.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(32, 375, 80, 23);

        jButton6.setBackground(new java.awt.Color(35, 31, 32));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/problem_2/InsertDM.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(32, 265, 93, 30);

        jButton10.setBackground(new java.awt.Color(35, 31, 32));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/problem_2/Draw DM.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(32, 430, 72, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/problem_2/Navigation Bar Logo DM.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(32, 32, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/problem_2/Line 5.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(250, 0, 10, 700);

        jButton1.setBackground(new java.awt.Color(35, 31, 32));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/problem_2/HomeDM.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(32, 210, 72, 30);

        jLabel5.setFont(new java.awt.Font("Cascadia Code", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 238, 238));
        jLabel5.setText("Developed by: ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(314, 50, 300, 70);

        jLabel4.setFont(new java.awt.Font("Candara Light", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 238, 238));
        jLabel4.setText("V 1.0");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(330, 530, 60, 70);

        amer.setFont(new java.awt.Font("Cascadia Code", 1, 30)); // NOI18N
        amer.setForeground(new java.awt.Color(238, 238, 238));
        amer.setText("Amer Shammout");
        amer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                amerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                amerMouseExited(evt);
            }
        });
        jPanel2.add(amer);
        amer.setBounds(310, 220, 380, 70);

        batool.setFont(new java.awt.Font("Cascadia Code", 1, 30)); // NOI18N
        batool.setForeground(new java.awt.Color(238, 238, 238));
        batool.setText("Batool AL-Lahham");
        batool.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                batoolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                batoolMouseExited(evt);
            }
        });
        jPanel2.add(batool);
        batool.setBounds(310, 340, 380, 70);

        george.setFont(new java.awt.Font("Cascadia Code", 1, 30)); // NOI18N
        george.setForeground(new java.awt.Color(238, 238, 238));
        george.setText("George Abboud");
        george.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                georgeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                georgeMouseExited(evt);
            }
        });
        jPanel2.add(george);
        george.setBounds(660, 220, 390, 70);

        amjad.setFont(new java.awt.Font("Cascadia Code", 1, 30)); // NOI18N
        amjad.setForeground(new java.awt.Color(238, 238, 238));
        amjad.setText("Amjad Hammouda");
        amjad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                amjadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                amjadMouseExited(evt);
            }
        });
        jPanel2.add(amjad);
        amjad.setBounds(660, 340, 350, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AboutPage about = new AboutPage();
        about.setVisible(true);
        about.pack();
        about.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        FormulaDM formula = new FormulaDM();
        formula.setVisible(true);
        formula.pack();
        formula.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ConvertDM convert = new ConvertDM();
        convert.setVisible(true);
        convert.pack();
        convert.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        InsertDM insert = new InsertDM();
        insert.setVisible(true);
        insert.pack();
        insert.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        DrawPageDM draw = new DrawPageDM();
        draw.setVisible(true);
        draw.pack();
        draw.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HomePageDM home = new HomePageDM();
        home.setVisible(true);
        home.pack();
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void amerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amerMouseEntered
        amer.setFont(new Font("Cascadia Code",Font.BOLD,34));
        amer.setForeground(Color.decode("#EAC067"));
    }//GEN-LAST:event_amerMouseEntered

    private void amerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amerMouseExited
        amer.setFont(new Font("Cascadia Code",Font.BOLD,30));
        amer.setForeground(Color.decode("#EEEEEE"));
    }//GEN-LAST:event_amerMouseExited

    private void batoolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batoolMouseEntered
        batool.setFont(new Font("Cascadia Code",Font.BOLD,33));
        batool.setForeground(Color.decode("#EAC067"));
    }//GEN-LAST:event_batoolMouseEntered

    private void batoolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batoolMouseExited
        batool.setFont(new Font("Cascadia Code",Font.BOLD,30));
        batool.setForeground(Color.decode("#EEEEEE"));
    }//GEN-LAST:event_batoolMouseExited

    private void georgeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_georgeMouseEntered
        george.setFont(new Font("Cascadia Code",Font.BOLD,34));
        george.setForeground(Color.decode("#EAC067"));
    }//GEN-LAST:event_georgeMouseEntered

    private void georgeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_georgeMouseExited
        george.setFont(new Font("Cascadia Code",Font.BOLD,30));
        george.setForeground(Color.decode("#EEEEEE"));
    }//GEN-LAST:event_georgeMouseExited

    private void amjadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amjadMouseEntered
        amjad.setFont(new Font("Cascadia Code",Font.BOLD,34));
        amjad.setForeground(Color.decode("#EAC067"));
    }//GEN-LAST:event_amjadMouseEntered

    private void amjadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amjadMouseExited
        amjad.setFont(new Font("Cascadia Code",Font.BOLD,30));
        amjad.setForeground(Color.decode("#EEEEEE"));
    }//GEN-LAST:event_amjadMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutPageDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutPageDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutPageDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutPageDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutPageDM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amer;
    private javax.swing.JLabel amjad;
    private javax.swing.JLabel batool;
    private javax.swing.JLabel george;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
